#ifndef LANCIUS_VERSION_H
#define LANCIUS_VERSION_H

#define LANCIUS_VERSION_MAJOR 11
#define LANCIUS_VERSION_MINOR 1
#define LANCIUS_VERSION_PATCH 0
#define LANCIUS_VERSION_MILESTONE 4

#define LANCIUS_VERSION_PHASE "S"
#define LANCIUS_VERSION_STRING "v11S"

#endif
