#!/usr/bin/env python3
"""
generate_oracles.py — v12A1 expanded oracle generator.

Generates ground-truth data for:
  sin, cos, exp, log (original v11S set)
  gamma, lgamma (v12A1 Lanczos)
  pow (v12A1 extended precision)
  large-argument sin/cos (v12A1 Payne-Hanek)

Requires: pip install mpmath
"""
import sys

try:
    from mpmath import mp, mpf, sin, cos, exp, log, gamma, power, pi, ln
except ImportError:
    print("ERROR: mpmath not installed. Run: pip install mpmath")
    sys.exit(1)

mp.dps = 50

# --- Original v11S trig inputs ---
trig_inputs = [
    0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 3.141592653589793,
    -0.5, -1.0, -1.5, -2.0, -3.0, -3.141592653589793,
    6.283185307179586, 10.0, 100.0, 1000.0, 10000.0, 1000000.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    -1e-10, -1e-50, -1e-100,
    0.1, 0.01, 0.001, 0.0001,
    7.0, 8.0, 9.0, 10.5, 15.0, 20.0, 50.0,
]

# --- v12A1: large-argument trig (Payne-Hanek) ---
large_trig_inputs = [1e10, 1e15, 1e20, 1e50, 1e100, 1e200, 1e300]

# --- Original v11S exp/log inputs ---
pos_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 100.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    1e10, 1e50, 1e100, 1e200, 1e300,
    0.1, 0.01, 0.001,
    2.718281828459045, 0.6931471805599453,
]

# --- v12A1: gamma inputs ---
gamma_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0, 10.0, 20.0, 50.0, 100.0, 171.0,
    0.1, 0.01, 0.001,
    -0.5, -1.5, -2.5, -3.5, -0.1, -0.9,
]

# --- v12A1: lgamma inputs ---
# MATHLIB_V12A1_ORACLE_LGAMMA_0001
lgamma_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 50.0, 100.0, 171.0,
    0.1, 0.01, 0.001,
    -0.5, -1.5, -2.5, -0.1,
]

# --- v12A1: pow inputs (base, exponent) ---
pow_inputs = [
    (2.0, 0.5), (2.0, 10.0), (2.0, -1.0), (2.0, 0.1),
    (3.0, 0.5), (10.0, 0.5), (10.0, 3.0), (10.0, -2.0),
    (0.5, 0.5), (0.5, 3.0), (100.0, 0.25),
    (1.5, 2.5), (2.718281828459045, 0.5),
    (7.0, 3.0), (7.0, -1.0), (7.0, 0.3333333333333333),
]


def to_double_str(mpf_val):
    f = float(mpf_val)
    if f != f:
        return "NAN"
    if f == float('inf'):
        return "INFINITY"
    if f == float('-inf'):
        return "-INFINITY"
    return f"{f:.17e}"


def generate_header():
    lines = [
        "/* Auto-generated by scripts/oracles/generate_oracles.py */",
        "/* MATHLIB_V12A1_ORACLE_EXPANSION */",
        "#ifndef MATHLIB_ORACLE_DATA_H",
        "#define MATHLIB_ORACLE_DATA_H",
        "",
        '#include "ml_core.h"',
        "#include <math.h>",
        "",
        "typedef struct { double input; double expected; } oracle_entry_t;",
        "typedef struct { double base; double exponent; double expected; } oracle_pow_entry_t;",
        "",
    ]

    # sin (original + large-arg)
    all_sin = trig_inputs + large_trig_inputs
    lines.append(f"static const oracle_entry_t oracle_sin[] = {{")
    for x in all_sin:
        lines.append(f"    {{{x:.17e}, {to_double_str(sin(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_sin_count = {len(all_sin)};")
    lines.append("")

    # cos (original + large-arg)
    all_cos = trig_inputs + large_trig_inputs
    lines.append(f"static const oracle_entry_t oracle_cos[] = {{")
    for x in all_cos:
        lines.append(f"    {{{x:.17e}, {to_double_str(cos(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_cos_count = {len(all_cos)};")
    lines.append("")

    # exp
    lines.append(f"static const oracle_entry_t oracle_exp[] = {{")
    for x in pos_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(exp(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_exp_count = {len(pos_inputs)};")
    lines.append("")

    # log
    lines.append(f"static const oracle_entry_t oracle_log[] = {{")
    for x in pos_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(log(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_log_count = {len(pos_inputs)};")
    lines.append("")

    # gamma
    lines.append(f"static const oracle_entry_t oracle_gamma[] = {{")
    for x in gamma_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(gamma(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_gamma_count = {len(gamma_inputs)};")
    lines.append("")

    # lgamma (log|gamma(x)|)
    lines.append(f"static const oracle_entry_t oracle_lgamma[] = {{")
    for x in lgamma_inputs:
        g = gamma(mpf(x))
        lg = log(abs(g))
        lines.append(f"    {{{x:.17e}, {to_double_str(lg)}}},")
    lines.append("};")
    lines.append(f"static const int oracle_lgamma_count = {len(lgamma_inputs)};")
    lines.append("")

    # pow
    lines.append(f"static const oracle_pow_entry_t oracle_pow[] = {{")
    for base, exponent in pow_inputs:
        result = power(mpf(base), mpf(exponent))
        lines.append(f"    {{{base:.17e}, {exponent:.17e}, {to_double_str(result)}}},")
    lines.append("};")
    lines.append(f"static const int oracle_pow_count = {len(pow_inputs)};")
    lines.append("")

    lines.append("#endif")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print("Generating v12A1 expanded oracle data (mpmath ground truth)...")
    header = generate_header()
    with open("tests/oracle_data.h", "w") as f:
        f.write(header)
    print("Oracle data written to tests/oracle_data.h")
