#ifndef MATHLIB_VERSION_H
#define MATHLIB_VERSION_H

/* MATHLIB_V12A1_BOOTSTRAP */
#define MATHLIB_VERSION_MAJOR 12
#define MATHLIB_VERSION_MINOR 1
#define MATHLIB_VERSION_PATCH 0
#define MATHLIB_VERSION_STRING "12.1.0-a1 (v12A1 development)"
#define MATHLIB_VERSION_TAG "v12A1"

#endif /* MATHLIB_VERSION_H */
