#ifndef LANCIUS_VERSION_H
#define LANCIUS_VERSION_H

#define LANCIUS_VERSION_MAJOR 11
#define LANCIUS_VERSION_MINOR 0
#define LANCIUS_VERSION_PATCH 0

#define LANCIUS_VERSION_PHASE "A1"
#define LANCIUS_VERSION_STRING "v11A1"

#endif
